### ISSUE TITLE
Official Release Checklist

### ISSUE THREAD

**Issue by mstksg** [mstksg/backprop-learn#1]
* [ ] would be nice to have convolutional filters
* [x] Waiting on the same things as https://github.com/mstksg/opto/issues/1 (vector needs to be updated on hackage)
* [ ] https://github.com/mstksg/opto needs to be released first
